name: Publish Gem

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup API token
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:rubygems_api_key: $KEY" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
        env:
          KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      - name: Build gem
        run: gem build --strict -o terutil.gem terutil.gemspec
      - name: Publish gem
        run: gem push terutil.gem

