name: Publish Gem

on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        steps:
          - run: gem build --strict -o terutil.gem terutil.gemspec
          - run: mkdir -p ~/.gem
          - run: echo -e "---\n:rubygems_api_key: ${secrets.RUBYGEMS_API_KEY}" > ~/.gem/credentials
          - run: gem push terutil.gem
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
          RELEASE_COMMAND: rake release
